document.open()
document.writeln('<div class="snipt-embed" onmouseover="document.getElementById(\'snipt-47173\').style.display = \'block\'; return false;" onmouseout="document.getElementById(\'snipt-47173\').style.display = \'none\'; return false;" style="position: relative;">')
document.writeln('<div class="highlight" style=""><pre style="')
document.writeln('                                     background-color: #1C1C1C;')
document.writeln('                                     border-radius: 5px;')
document.writeln('                                     color: #D0D0D0;')
document.writeln('                                     display: block;')
document.writeln('                                     text-align: center;')
document.writeln('                                     font: 11px Monaco, monospace;')
document.writeln('                                     margin: 0;')
document.writeln('                                     overflow: auto;')
document.writeln('                                     padding: 15px;')
document.writeln('                                     -webkit-border-radius: 5px;')
document.writeln('                                     -moz-border-radius: 5px;')
document.writeln('                                     ; line-height: 125%"><span style="color: #d0d0d0">perl -p -i -e</span> <span style="color: #ed9d13">&#39;s/foo/bar/gi&#39;</span>')
document.writeln('</pre></div>')
document.writeln('')
document.writeln('</div>')
document.close()
