#!/usr/bin/env bash
# Standalone script for archive functions

if [ -z "$1" ]; then
    echo "Usage: barchive [extract|encrypt|decrypt] [args]"
    exit 1
fi

operation="$1"; shift

extract_one() {
    case "$1" in
        *.tar.bz2) tar xjf "$1" ;; *.tar.gz) tar xzf "$1" ;; *.bz2) bunzip2 "$1" ;;
        *.rar) unrar x "$1" ;; *.gz) gunzip "$1" ;; *.tar) tar xf "$1" ;;
        *.tbz2) tar xjf "$1" ;; *.tgz) tar xzf "$1" ;; *.zip) unzip "$1" ;;
        *.Z) uncompress "$1" ;; *.7z) 7z x "$1" ;; *.xz) unxz "$1" ;;
        *) echo "Cannot extract $1"; return 1 ;;
    esac
}

case "$operation" in
    extract) extract_one "$1" ;;
    encrypt)
        if [ -z "$1" ] || [ -z "$2" ]; then echo "Usage: barchive encrypt INPUT OUTPUT"; exit 1; fi
        openssl des3 -salt -in "$1" -out "$2" ;;
    decrypt)
        if [ -z "$1" ] || [ -z "$2" ]; then echo "Usage: barchive decrypt INPUT OUTPUT"; exit 1; fi
        openssl des3 -d -in "$1" -out "$2" ;;
    *) echo "Unknown operation: $operation" ;;
esac
