#!/usr/bin/env bash
# Standalone script for system management

if [ -z "$1" ]; then
    echo "Usage: bsys [search|install|upgrade] [args]"
    exit 1
fi

operation="$1"; shift
pkg_manager=""
if command -v pacman &>/dev/null; then pkg_manager="pacman";
elif command -v apt &>/dev/null; then pkg_manager="apt";
elif command -v dnf &>/dev/null; then pkg_manager="dnf";
elif command -v zypper &>/dev/null; then pkg_manager="zypper";
else echo "Unsupported package manager" && exit 1; fi

case "$operation" in
    search)
        case "$pkg_manager" in
            apt) apt search "$@" ;; pacman) pacman -Ss "$@" ;;
            dnf) dnf search "$@" ;; zypper) zypper search "$@" ;;
        esac ;;
    install)
        case "$pkg_manager" in
            apt) sudo apt update && sudo apt install -y "$@" ;;
            pacman) sudo pacman -S --noconfirm "$@" ;;
            dnf) sudo dnf install -y "$@" ;;
            zypper) sudo zypper install -y "$@" ;;
        esac ;;
    upgrade)
        case "$pkg_manager" in
            apt) sudo apt update && sudo apt full-upgrade -y && sudo apt autoremove --purge -y ;;
            pacman) sudo pacman -Syu --noconfirm ;;
            dnf) sudo dnf upgrade --refresh -y && sudo dnf autoremove -y ;;
            zypper) sudo zypper refresh && sudo zypper update -y ;;
        esac ;;
    *) echo "Unknown operation: $operation" ;;
esac
