document.open()
document.writeln('<div class="snipt-embed" onmouseover="document.getElementById(\'snipt-47174\').style.display = \'block\'; return false;" onmouseout="document.getElementById(\'snipt-47174\').style.display = \'none\'; return false;" style="position: relative;">')
document.writeln('<div class="highlight" style=""><pre style="')
document.writeln('                                     background-color: #1C1C1C;')
document.writeln('                                     border-radius: 5px;')
document.writeln('                                     color: #D0D0D0;')
document.writeln('                                     display: block;')
document.writeln('                                     text-align: center;')
document.writeln('                                     font: 11px Monaco, monospace;')
document.writeln('                                     margin: 0;')
document.writeln('                                     overflow: auto;')
document.writeln('                                     padding: 15px;')
document.writeln('                                     -webkit-border-radius: 5px;')
document.writeln('                                     -moz-border-radius: 5px;')
document.writeln('                                     ; line-height: 125%"><span style="color: #d0d0d0">perl</span> <span style="color: #d0d0d0">-p</span> <span style="color: #d0d0d0">-i</span> <span style="color: #d0d0d0">-e</span> <span style="color: #ed9d13">&#39;s/SOME_NAME/Kris/gi&#39;</span> <span style="color: #d0d0d0">./*.txt</span>')
document.writeln('</pre></div>')
document.writeln('')
document.writeln('<div style="background-color: #111; color: #D0D0D0; float: right; padding: 5px 10px; -moz-border-radius-topleft: 5px; -webkit-border-top-left-radius: 5px; border-top-left-radius: 5px; -moz-border-radius-bottomright: 5px; -webkit-border-bottom-right-radius: 5px; border-bottom-right-radius: 5px; font: 11px Arial,Sans-Serif; display: none; position: absolute; bottom: 0; right: 0;" id="snipt-47174">code hosted by <a href="/web/20131029102423/https://snipt.net/krisrmgua/perl-p-i-e-replace-name-in-all-text-files-in-current-directory?key=70f25d795bca845b04e8d273655d6bd8" style="color: #0084FF; text-decoration: none;">snipt.net</a></div>')
document.writeln('</div>')
document.close()
